# set os for the container
FROM ibmcom/iib-mq-server
#FROM ubuntu/mysql:8.0-20.04_beta
SHELL ["/bin/bash", "-c"]
#    RUN apt-get update && apt-get upgrade
#    RUN apt-get install nano
#    RUN echo 'Start des Containers'
ENV LICENSE=accept
#RUN echo "root:1234" | chpasswd
CMD su - root

#Setting the basic environment for IIB
#WORKDIR /home/iibadmin  
#USER iibadmin
#    RUN echo ". /opt/iib-10.0.0.19/server/bin/mqsiprofile" > .profile




